// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4X2UoflQoj2uGsn4__i65Iu9g9qnjN0Y',
    appId: '1:1096895928039:web:d14d296dced123d994f442',
    messagingSenderId: '1096895928039',
    projectId: 'flutter-firebase-test-fe5c1',
    authDomain: 'flutter-firebase-test-fe5c1.firebaseapp.com',
    storageBucket: 'flutter-firebase-test-fe5c1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtBMGivsT3YmCMpeXHaX-0Dbsv5Ltc57U',
    appId: '1:1096895928039:android:3dc1a49238c6c8ad94f442',
    messagingSenderId: '1096895928039',
    projectId: 'flutter-firebase-test-fe5c1',
    storageBucket: 'flutter-firebase-test-fe5c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVxLiOBo8WBfWN7G69LBoGGTo6gTwsbD8',
    appId: '1:1096895928039:ios:2dc9a05bfba22c9994f442',
    messagingSenderId: '1096895928039',
    projectId: 'flutter-firebase-test-fe5c1',
    storageBucket: 'flutter-firebase-test-fe5c1.appspot.com',
    iosClientId: '1096895928039-udqr2dn8kpur75luunr7kp5fdg65nbvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVxLiOBo8WBfWN7G69LBoGGTo6gTwsbD8',
    appId: '1:1096895928039:ios:2dc9a05bfba22c9994f442',
    messagingSenderId: '1096895928039',
    projectId: 'flutter-firebase-test-fe5c1',
    storageBucket: 'flutter-firebase-test-fe5c1.appspot.com',
    iosClientId: '1096895928039-udqr2dn8kpur75luunr7kp5fdg65nbvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
